#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h

apt install wget pigz

cd /drone/src # Where to download cccahe

echo "|| Downloading CCACHE ||" # will remove it after getting ccache backup from transfer.sh & use newlink
#git clone --depth=1 https://who-em-i:$gh_token@github.com/ImPrashantt/ccache_backup.git ccache
#time curl -L https://free.keep.sh/Vvr4LMqPG4A1lXtd/ccache_backup.zip.001 > ccache_backup.zip.001
#time curl -L https://free.keep.sh/xVZIS4zN9BtVeCaA/ccache_backup.zip.002 > ccache_backup.zip.002

echo "|| Extracting CCACHE ||"
#7za x ccache_backup.zip.001
#time tar xf ccache.tar.gz  # Extract ccache so ci can use it
#rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the upload ccache process
#rm -rf ccache_backup.zip.*
